Zurita.Mvc/ViewModels/MisAdopciones/MiAdopcionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Zurita.Mvc.ViewModels.Mascota;
using Zurita.Mvc.ViewModels.SolicitudAdopcion;

namespace Zurita.Mvc.ViewModels.MisAdopciones
{
    public class MiAdopcionViewModel
    {

        public MascotaViewModel Mascota { get; set; }

        public SolicitudAdopcionViewModel Solicitud { get; set; }
    }
}

Zurita.Mvc/Controllers/MascotaController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Zurita.Models;
using Zurita.Mvc.ViewModels.Mascota;
using Zurita.UnitOfWork;

namespace Zurita.Mvc.Controllers
{
    public class MascotaController : BaseController
    {

        public MascotaController(ILog log, IUnitOfWork unit) : base(log, unit)
        {
        }

        // GET: Mascota
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Lista()
        {
            var modelos = _unit.Mascotas.GetList();
            var lista = new List<MascotaViewModel>();

            foreach (var modelo in modelos)
            {
                lista.Add(ObtenerMascotaDeModelo(modelo));
            }

            return PartialView(lista);
        }

        [HttpGet]
        public PartialViewResult Create()
        {
            ViewBag.Sexos = ObtenerSexos();
            ViewBag.Especies = ObtenerEspeciesSelect();
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(MascotaViewModel viewModel)
        {
            if (ModelState.IsValid)
            {

                var mascota = ObtenerMascotaDeViewModel(viewModel);

                _unit.Mascotas.Insert(mascota);
                return RedirectToAction("Index");
            }

            return PartialView(viewModel);
        }


        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            ViewBag.Sexos = ObtenerSexos();
            ViewBag.Especies = ObtenerEspeciesSelect();


            return PartialView(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }

        [HttpPost]
        public ActionResult Edit(MascotaViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var mascota = ObtenerMascotaDeViewModel(viewModel);

            if (_unit.Mascotas.Update(mascota))
            {
                return RedirectToAction("Index");
            }
            return PartialView(viewModel);
        }


        [HttpGet]
        public PartialViewResult Delete(int id)
        {
            return PartialView(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }


        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (_unit.Mascotas.Delete(id))
            {
                return RedirectToAction("Index");
            }

            return PartialView(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }

        [HttpGet]
        public PartialViewResult Details(int id)
        {
            return PartialView(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult DetallePublico(int id)
        {
            ViewBag.SolicitudActual = 0;
            ViewBag.EstadoActual = "";
            if (Request.IsAuthenticated)
            {
                var solicitud = _unit.SolicitudesAdopcion.ObtenerPorMascotaYUsuario(id, ObtenerUsernameActual());
                if (solicitud != null)
                {
                    ViewBag.SolicitudActual = solicitud.SolicitudAdopcionId;
                    ViewBag.EstadoActual = solicitud.Estado;
                }
            }
            return View(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }

        [HttpPost]
        public ActionResult SubirFoto()
        {

            string path = System.Web.HttpContext.Current.Server.MapPath("~/Subidas/");

            HttpPostedFile postedFile = System.Web.HttpContext.Current.Request.Files[0];

            var nombreArchivo = Guid.NewGuid() + Path.GetExtension(postedFile.FileName);

            postedFile.SaveAs(path + nombreArchivo);
            return Json(new
            {
                nombreArchivo
            });
        }

        [HttpPost]
        public ActionResult SolicitarAdopcion(PeticionAdoptarMascotaViewModel peticion)
        {
            var username = ObtenerUsernameActual();
            var usuario = _unit.Usuarios.BuscarPorUsuario(username);
            var solicitudAdocion = new SolicitudAdopcion()
            {
                Username = username,
                MascotaId = peticion.IdMascota,
                ApellidoMaterno = usuario.Apellidos,
                ApellidoPaterno = usuario.Apellidos,
                Direccion = usuario.Direccion,
                Estado = "Nuevo",
                Fecha = DateTime.Now,
                Motivo = "Adopción",
                Nombres = usuario.Nombres
            };

            var id = _unit.SolicitudesAdopcion.Insert(solicitudAdocion);


            var cuerpoEmail = $"Hola {usuario.Nombres} hemos recibido tu solicitud de adopcion";

            EnviarCorreo("Solicitud recibida", cuerpoEmail, new List<string>() { usuario.Correo });

            return Json(new
            {
                id,
                suceso = true
            });
        }

        [HttpPost]
        public ActionResult CancelarSolicitud(PeticionCancelarSolicitudAdopcionViewModel peticion)
        {
            var username = ObtenerUsernameActual();
            var usuario = _unit.Usuarios.BuscarPorUsuario(username);


            _unit.SolicitudesAdopcion.Delete(peticion.IdSolicitudAdopcion);


            var cuerpoEmail = $"Hola {usuario.Nombres} hemos recibido tu solicitud de cancelación de la adopción";

            EnviarCorreo("Solicitud cancelada", cuerpoEmail, new List<string>() { usuario.Correo });

            return Json(new
            {
                suceso = true
            });
        }


    }
}

Zurita.Mvc/Controllers/MisAdopcionesController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zurita.Mvc.ViewModels.MisAdopciones;
using Zurita.Mvc.ViewModels.SolicitudAdopcion;
using Zurita.UnitOfWork;

namespace Zurita.Mvc.Controllers
{
    public class MisAdopcionesController : BaseController
    {


        public MisAdopcionesController(ILog log, IUnitOfWork unit) : base(log, unit)
        {
        }

        // GET: MisAdopciones
        public ActionResult Index()
        {

            var lista = new List<SolicitudAdopcionViewModel>();

            foreach (var entidad in _unit.SolicitudesAdopcion.GetList(ObtenerUsernameActual()))
            {
                lista.Add(ObtenerSolicitudDeModelo(entidad));
            }

            return View(lista);
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            var solicitud = _unit.SolicitudesAdopcion.GetById(id);
            if (solicitud == null)
            {
                return RedirectToAction("Index");
            }

            var mascota = _unit.Mascotas.GetById(solicitud.MascotaId.Value);

            var viewModel = new MiAdopcionViewModel()
            {
                Mascota = ObtenerMascotaDeModelo(mascota),
                Solicitud = ObtenerSolicitudDeModelo(solicitud)
            };


            return View(viewModel);
        }
    }
}

Zurita.Mvc/Views/MisAdopciones/Detalle.cshtml
@model Zurita.Mvc.ViewModels.MisAdopciones.MiAdopcionViewModel
@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_LayoutVistaPublica.cshtml";
}

@section BannerSuperior{
    <section id="page-title" data-bg-parallax="@Url.Content("~/Content/Imagenes/banner_detalle_mascota.png")"></section>

}

<input type="hidden" id="__ID" value="@Model.Solicitud.SolicitudAdopcionId" />
<input type="hidden" id="__URL_CANCELAR_ADOPCION" value="@Url.Action("CancelarSolicitud","Mascota")" />

<input type="hidden" id="__URL_SOLICITUDES" value="@Url.Action("Index","MisAdopciones")" />


<div class="container">
    <h1>Adopción @Model.Mascota.Nombre</h1>
    <div class="breadcrumb titulo-simple">
        <ul>
            <li>
                <a href="@Url.Action("Index","MisAdopciones")">Mis Adopciones</a>
            </li>
            <li>
                <a href="@Url.Action("Detalle","MisAdopciones", new { id = Model.Solicitud.SolicitudAdopcionId })" class="active">@Model.Mascota.Nombre</a>
            </li>
        </ul>
    </div>
</div>

<div class="product">


    <div class="tabs tabs-folder">
        <ul class="nav nav-tabs" id="myTab3" role="tablist">
            <li class="nav-item">
                <a class="nav-link active show" id="profile-tab" data-toggle="tab" href="#profile3" role="tab" aria-controls="profile" aria-selected="true">
                    <i class="fa fa-align-justify"></i>Adopción
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact3" role="tab" aria-controls="contact" aria-selected="false"><i class="fa fa-info"></i>Mascota</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent3">
            <div class="tab-pane fade active show" id="profile3" role="tabpanel" aria-labelledby="profile-tab">

                <table class="table table-striped table-bordered">
                    <tbody>
                        <tr>
                            <td>Fecha</td>
                            <td>@Model.Solicitud.Fecha</td>
                        </tr>
                        <tr>
                            <td>Motivo</td>
                            <td>@Model.Solicitud.Motivo</td>
                        </tr>
                        <tr>
                            <td>Estado</td>
                            <td>@Model.Solicitud.Estado</td>
                        </tr>
                    </tbody>
                </table>

                @if (Model.Solicitud.Estado.Equals("Nuevo", StringComparison.OrdinalIgnoreCase))
                {
                    <a class="btn btn-danger" onclick="detalleSolicitud.cancelarAdopcion();">Cancelar Solicitud</a>
                }

            </div>
            <div class="tab-pane fade" id="contact3" role="tabpanel" aria-labelledby="contact-tab">

                <div class="row m-b-40">
                    <div class="col-lg-5">
                        <div class="product-image">
                            <img alt="" src="@Url.Content("~/Subidas/" + Model.Mascota.Foto)">
                        </div>
                    </div>
                    <div class="col-lg-7">
                        <div class="product-description">
                            <div class="product-category">@Model.Mascota.Especie</div>
                            <div class="product-title">
                                <h1><a href="#">@Model.Mascota.Nombre</a></h1>
                            </div>
                            <div class="seperator m-b-10 m-t-10"></div>
                            <p>
                                @Model.Mascota.Descripcion
                            </p>
                            <div class="seperator m-t-20 m-b-10"></div>
                        </div>
                    </div>
                </div>

                <table class="table table-striped table-bordered">
                    <tbody>
                        <tr>
                            <td>Nacimiento</td>
                            <td>@Model.Mascota.Nacimiento</td>
                        </tr>
                        <tr>
                            <td>Color</td>
                            <td>@Model.Mascota.Color</td>
                        </tr>
                        <tr>
                            <td>Sexo</td>
                            <td>
                                @if ("H".Equals(@Model.Mascota.Sexo, StringComparison.OrdinalIgnoreCase))
                                {
                                    <span>Hembra</span>
                                }
                                else if ("M".Equals(@Model.Mascota.Sexo, StringComparison.OrdinalIgnoreCase))
                                {
                                    <span>Macho</span>
                                }
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>
@section Scripts {


    <script src="~/Content/js/detalleSolicitud.js" type="text/javascript"></script>

}

Zurita.Mvc/Views/MisAdopciones/Index.cshtml
@model IEnumerable<Zurita.Mvc.ViewModels.SolicitudAdopcion.SolicitudAdopcionViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutVistaPublica.cshtml";
}

<div class="container">
    <h1>Mi adopciones</h1>
    <div class="breadcrumb titulo-simple">
        <ul>
            <li>
                <a href="javascript:void(0);">Mi usuario</a>
            </li>
            <li>
                <a href="@Url.Action("Index","MisAdopciones")" class="active">Mis adopciones</a>
            </li>
        </ul>
    </div>
</div>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Motivo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mascota)
            </th>
            <th></th>
        </tr>

    </thead>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Motivo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mascota)
            </td>
            <td>

                <a class="btn btn-success" href="@Url.Action("Detalle","MisAdopciones", new { id = item.SolicitudAdopcionId })">
                    <i class="icon-file-text"></i>
                    Detalle
                </a>

            </td>
        </tr>
    }

</table>