Zurita.Mvc/Controllers/MascotaController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Zurita.Models;
using Zurita.Mvc.ViewModels.Mascota;
using Zurita.UnitOfWork;

namespace Zurita.Mvc.Controllers
{
    public class MascotaController : BaseController
    {

        public MascotaController(ILog log, IUnitOfWork unit) : base(log, unit)
        {
        }

        // GET: Mascota
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Lista()
        {
            var modelos = _unit.Mascotas.GetList();
            var lista = new List<MascotaViewModel>();

            foreach (var modelo in modelos)
            {
                lista.Add(ObtenerMascotaDeModelo(modelo));
            }

            return PartialView(lista);
        }

        [HttpGet]
        public PartialViewResult Create()
        {
            ViewBag.Sexos = ObtenerSexos();
            ViewBag.Especies = ObtenerEspeciesSelect();
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(MascotaViewModel viewModel)
        {
            if (ModelState.IsValid)
            {

                var mascota = ObtenerMascotaDeViewModel(viewModel);

                _unit.Mascotas.Insert(mascota);
                return RedirectToAction("Index");
            }

            return PartialView(viewModel);
        }


        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            ViewBag.Sexos = ObtenerSexos();
            ViewBag.Especies = ObtenerEspeciesSelect();


            return PartialView(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }

        [HttpPost]
        public ActionResult Edit(MascotaViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var mascota = ObtenerMascotaDeViewModel(viewModel);

            if (_unit.Mascotas.Update(mascota))
            {
                return RedirectToAction("Index");
            }
            return PartialView(viewModel);
        }


        [HttpGet]
        public PartialViewResult Delete(int id)
        {
            return PartialView(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }


        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (_unit.Mascotas.Delete(id))
            {
                return RedirectToAction("Index");
            }

            return PartialView(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }

        [HttpGet]
        public PartialViewResult Details(int id)
        {
            return PartialView(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult DetallePublico(int id)
        {
            ViewBag.SolicitudActual = 0;
            ViewBag.EstadoActual = "";
            if (Request.IsAuthenticated)
            {
                var solicitud = _unit.SolicitudesAdopcion.ObtenerPorMascotaYUsuario(id, ObtenerUsernameActual());
                if (solicitud != null)
                {
                    ViewBag.SolicitudActual = solicitud.SolicitudAdopcionId;
                    ViewBag.EstadoActual = solicitud.Estado;
                }
            }
            return View(ObtenerMascotaDeModelo(_unit.Mascotas.GetById(id)));
        }

        [HttpPost]
        public ActionResult SubirFoto()
        {

            string path = System.Web.HttpContext.Current.Server.MapPath("~/Subidas/");

            HttpPostedFile postedFile = System.Web.HttpContext.Current.Request.Files[0];

            var nombreArchivo = Guid.NewGuid() + Path.GetExtension(postedFile.FileName);

            postedFile.SaveAs(path + nombreArchivo);
            return Json(new
            {
                nombreArchivo
            });
        }

        [HttpPost]
        public ActionResult SolicitarAdopcion(PeticionAdoptarMascotaViewModel peticion)
        {
            var username = ObtenerUsernameActual();
            var usuario = _unit.Usuarios.BuscarPorUsuario(username);
            var solicitudAdocion = new SolicitudAdopcion()
            {
                Username = username,
                MascotaId = peticion.IdMascota,
                ApellidoMaterno = usuario.Apellidos,
                ApellidoPaterno = usuario.Apellidos,
                Direccion = usuario.Direccion,
                Estado = "Nuevo",
                Fecha = DateTime.Now,
                Motivo = "Adopción",
                Nombres = usuario.Nombres
            };

            var id = _unit.SolicitudesAdopcion.Insert(solicitudAdocion);


            var cuerpoEmail = $"Hola {usuario.Nombres} hemos recibido tu solicitud de adopcion";

            EnviarCorreo("Solicitud recibida", cuerpoEmail, new List<string>() { usuario.Correo });

            return Json(new
            {
                id,
                suceso = true
            });
        }

        [HttpPost]
        public ActionResult CancelarSolicitud(PeticionCancelarSolicitudAdopcionViewModel peticion)
        {
            var username = ObtenerUsernameActual();
            var usuario = _unit.Usuarios.BuscarPorUsuario(username);


            _unit.SolicitudesAdopcion.Delete(peticion.IdSolicitudAdopcion);


            var cuerpoEmail = $"Hola {usuario.Nombres} hemos recibido tu solicitud de cancelación de la adopción";

            EnviarCorreo("Solicitud cancelada", cuerpoEmail, new List<string>() { usuario.Correo });

            return Json(new
            {
                suceso = true
            });
        }


    }
}

Zurita.Mvc/Controllers/UsuarioController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zurita.Models;
using Zurita.Mvc.ViewModels.Usuario;
using Zurita.UnitOfWork;

namespace Zurita.Mvc.Controllers
{
    public class UsuarioController : BaseController
    {


        public UsuarioController(ILog log, IUnitOfWork unit) : base(log, unit)
        {
        }

        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Lista()
        {
            var modelos = _unit.Usuarios.GetList();
            var lista = new List<UsuarioViewModel>();

            foreach (var modelo in modelos)
            {
                lista.Add(ObtenerDeModelo(modelo));
            }

            return PartialView(lista);
        }

        [HttpGet]
        public PartialViewResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(UsuarioViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var usuario = ObtenerDeViewModel(viewModel);

                _unit.Usuarios.Insert(usuario);
                return RedirectToAction("Index");
            }

            return PartialView(viewModel);
        }

        [HttpGet]
        public PartialViewResult Edit(string id)
        {

            return PartialView(ObtenerDeModelo(_unit.Usuarios.BuscarPorUsuario(id)));
        }

        [HttpPost]
        public ActionResult Edit(UsuarioViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var usuario = ObtenerDeViewModel(viewModel);

            if (_unit.Usuarios.Update(usuario))
            {
                return RedirectToAction("Index");
            }
            return PartialView(viewModel);
        }


        [HttpGet]
        public PartialViewResult Delete(string id)
        {
            return PartialView(ObtenerDeModelo(_unit.Usuarios.BuscarPorUsuario(id)));
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(string id)
        {
            if (_unit.Usuarios.Delete(id))
            {
                return RedirectToAction("Index");
            }

            return PartialView(ObtenerDeModelo(_unit.Usuarios.BuscarPorUsuario(id)));
        }

        [HttpGet]
        public PartialViewResult Details(string id)
        {
            return PartialView(ObtenerDeModelo(_unit.Usuarios.BuscarPorUsuario(id)));
        }

        private UsuarioViewModel ObtenerDeModelo(Usuario usuario)
        {
            if (usuario == null)
            {
                return null;
            }

            var viewModel = new UsuarioViewModel()
            {
                Apellidos = usuario.Apellidos,
                Email = usuario.Correo,
                Direccion = usuario.Direccion,
                EsAdministrador = usuario.EsAdministrador,
                Nombres = usuario.Nombres,
                Password = usuario.Password,
                Telefono = usuario.Telefono,
                Username = usuario.Username
            };


            return viewModel;
        }

        private Usuario ObtenerDeViewModel(UsuarioViewModel viewModel)
        {
            if (viewModel == null)
            {
                return null;
            }

            var modelo = new Usuario()
            {
                Apellidos = viewModel.Apellidos,
                Correo = viewModel.Email,
                Direccion = viewModel.Direccion,
                EsAdministrador = viewModel.EsAdministrador,
                Nombres = viewModel.Nombres,
                Password = viewModel.Password,
                Telefono = viewModel.Telefono,
                Username = viewModel.Username
            };
            return modelo;
        }
    }
}

Zurita.Mvc/Controllers/VisitaHogarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using log4net;
using Zurita.Models;
using Zurita.Mvc.ViewModels.VisitaHogar;
using Zurita.UnitOfWork;

namespace Zurita.Mvc.Controllers
{
    public class VisitaHogarController : BaseController
    {

        public VisitaHogarController(ILog log, IUnitOfWork unit) : base(log, unit)
        {
        }

        // GET: VisitaHogar
        public ActionResult Index()
        {
            var lista = new List<VisitaHogarViewModel>();

            foreach (var entidad in _unit.VisitasHogar.GetList())
            {
                lista.Add(new VisitaHogarViewModel()
                {
                    Direccion = entidad.Direccion,
                    Fecha = entidad.Fecha,
                    MascotaId = entidad.MascotaId,
                    Motivo = entidad.Motivo,
                    Observacion = entidad.Observacion,
                    VisitaHogarId = entidad.VisitaHogarId
                });
            }

            return View(lista);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Mascotas = ObtenerMascotasSelect();
            return View();
        }

        [HttpPost]
        public ActionResult Create(VisitaHogarViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var entidad = new VisitaHogar()
                {
                    Direccion = viewModel.Direccion,
                    Fecha = viewModel.Fecha,
                    MascotaId = viewModel.MascotaId,
                    Motivo = viewModel.Motivo,
                    Observacion = viewModel.Observacion,
                    VisitaHogarId = viewModel.VisitaHogarId
                };

                _unit.VisitasHogar.Insert(entidad);
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var entidad = _unit.VisitasHogar.GetById(id);

            var viewModel = new VisitaHogarViewModel()
            {
                Direccion = entidad.Direccion,
                Fecha = entidad.Fecha,
                MascotaId = entidad.MascotaId,
                Motivo = entidad.Motivo,
                Observacion = entidad.Observacion,
                VisitaHogarId = entidad.VisitaHogarId
            };

            ViewBag.Mascotas = ObtenerMascotasSelect();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(VisitaHogarViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var entidad = new VisitaHogar()
                {
                    Direccion = viewModel.Direccion,
                    Fecha = viewModel.Fecha,
                    MascotaId = viewModel.MascotaId,
                    Motivo = viewModel.Motivo,
                    Observacion = viewModel.Observacion,
                    VisitaHogarId = viewModel.VisitaHogarId
                };

                if (_unit.VisitasHogar.Update(entidad))
                {
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }


            return View(viewModel);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var entidad = _unit.VisitasHogar.GetById(id);

            var viewModel = new VisitaHogarViewModel()
            {
                Direccion = entidad.Direccion,
                Fecha = entidad.Fecha,
                MascotaId = entidad.MascotaId,
                Motivo = entidad.Motivo,
                Observacion = entidad.Observacion,
                VisitaHogarId = entidad.VisitaHogarId
            };

            return View(viewModel);
        }


        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (_unit.VisitasHogar.Delete(id))
            {
                return RedirectToAction("Index");
            }
            var entidad = _unit.VisitasHogar.GetById(id);

            var viewModel = new VisitaHogarViewModel()
            {
                Direccion = entidad.Direccion,
                Fecha = entidad.Fecha,
                MascotaId = entidad.MascotaId,
                Motivo = entidad.Motivo,
                Observacion = entidad.Observacion,
                VisitaHogarId = entidad.VisitaHogarId
            };

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var entidad = _unit.VisitasHogar.GetById(id);

            var viewModel = new VisitaHogarViewModel()
            {
                Direccion = entidad.Direccion,
                Fecha = entidad.Fecha,
                MascotaId = entidad.MascotaId,
                Motivo = entidad.Motivo,
                Observacion = entidad.Observacion,
                VisitaHogarId = entidad.VisitaHogarId
            };

            return View(viewModel);
        }

    }
}

Zurita.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Adopción de Mascotas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Adopción de Mascotas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Mascotas", "Index", "Mascota")</li>
                    <li>@Html.ActionLink("Visitas Médicas", "Index", "VisitaMedica")</li>
                    <li>@Html.ActionLink("Visitas Hogar", "Index", "VisitaHogar")</li>
                    <li>@Html.ActionLink("Solucitudes Adopción", "Index", "SolicitudAdopcion")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Adopción de Mascotas</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Zurita.Mvc/Views/Shared/_LayoutVistaPublica.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="INSPIRO" />
    <meta name="description" content="Themeforest Template Polo, html template">
    <link rel="icon" type="image/png" href="images/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Document title -->
    <title>MASCOTAS - @ViewBag.Title</title>
    <!-- Stylesheets & Fonts -->
    <link href="~/Content/Temas/Publico/css/plugins.css" rel="stylesheet">
    <link href="~/Content/Temas/Publico/css/style.css" rel="stylesheet">
    <link href="~/Content/Temas/Publico/css/plugins.css" rel="stylesheet">

    <link href="~/Content/css/public.css" rel="stylesheet">

</head>
<body>
    <div class="body-inner">

        <header id="header" data-transparent="true" data-fullwidth="true">
            <div class="header-inner">
                <div class="container">
                    <!--Logo-->
                    <div id="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <span class="logo-default">MASCOTAS</span>
                            <span class="logo-dark">MASCOTAS</span>
                        </a>
                    </div>
                    <!--End: Logo-->
                    <!-- Search -->
                    <!-- end: search -->
                    <!--Header Extras-->
                    <!--end: Header Extras-->
                    <!--Navigation Resposnive Trigger-->
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>
                    <!--end: Navigation Resposnive Trigger-->
                    <!--Navigation-->
                    <div id="mainMenu">
                        <div class="container">
                            <nav>
                                @*@Html.Partial("_Menu")*@

                                @Html.Action("MenuInfo", "Account")
                            </nav>
                        </div>
                    </div>
                    <!--END: NAVIGATION-->
                </div>
            </div>
        </header>

        @RenderSection("BannerSuperior", required: false)

        <section id="page-content">
            <div class="container">
                @RenderBody()
            </div>
        </section>
        <footer id="footer">
            <div class="copyright-content">
                <div class="container">
                    <div class="copyright-text text-center">&copy; 2020 MASCOTAS - Todos los derechos reservados.<a href="//www.inspiro-media.com" target="_blank" rel="noopener"> INSPIRO</a> </div>
                </div>
            </div>
        </footer>

    </div>


    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
    <!--Plugins-->
    <script src="~/Content/Temas/Publico/js/jquery.js"></script>
    <script src="~/Content/Temas/Publico/js/plugins.js"></script>
    <script src="~/Scripts/sweetalert2.js"></script>
    <!--Template functions-->
    <script src="~/Content/Temas/Publico/js/functions.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Zurita.Mvc/Views/Shared/_Menu.cshtml
<ul>
    <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
    <li><a href="index.html">Mascotas</a></li>

    @if (!Request.IsAuthenticated)
    {
        <li class="dropdown">
            <a href="@Url.Action("Login", "Account")">Acceso</a>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("Login", "Account")">Ingreso</a></li>
                <li><a href="@Url.Action("Registro", "Account")">Registro Usuario</a></li>
            </ul>
        </li>
    }

    @if (Request.IsAuthenticated)
    {
        <li class="dropdown">
            <a href="javascript:void(0);">Administración</a>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("Index", "Mascota")">Mascotas</a></li>
                <li><a href="@Url.Action("Index", "SolicitudAdopcion")">Solicitudes</a></li>
                <li><a href="@Url.Action("Index", "VisitaHogar")">Visitas Hogar</a></li>
                <li><a href="@Url.Action("Index", "VisitaMedica")">Visitas Médicas</a></li>
                <li><a href="@Url.Action("Index", "Usuario")">Usuarios</a></li>

            </ul>
        </li>
    }


    @if (Request.IsAuthenticated)
    {
        <li class="dropdown">
            <a href="javascript:void(0);">Mi Usuario</a>
            <ul class="dropdown-menu">
                <li><a href="index.html">Mi Usuario</a></li>
                <li><a href="index.html">Mis Adopciones</a></li>
                <li><a href="@Url.Action("Logout", "Account")">Salir</a></li>
            </ul>
        </li>
    }

</ul>